#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: TaoAlpha
title: TaoAlpha's Blog
author_info: TaoAlpha
description: Driven by Passion

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/4335753

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: iamzhoutao92@gmail.com
  facebook: http://www.facebook.com/zzgary
  flickr: 
  github: taoalpha/
  instagram: 
  linkedin: 
  pinterest: 
  rss: http://taoalpha.github.io # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: zzgary92
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# for duoshuo
comments :
  provider : duoshuo
  duoshuo :
    short_name : taoalpha
    api : 
      commentCount: "http://api.duoshuo.com/threads/counts.json?short_name=taoalpha&threads="

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-46725017-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://taoalpha.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/blog"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge 
permalink: /:year/:month/:day/:title.html
paginate: 15
paginate_path: "page:num/"
lsi: true

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
#sass:
#  sass_dir: _scss
#  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - Rakefile
    - README.md

authors:
    taoalpha:
        display_name: TaoAlpha
        avatar: https://avatars3.githubusercontent.com/u/4335753?v=3&s=40
        email: iamzhoutao92@gmail.com
        web: http://zzgary.info
        github: taoalpha

cats:
  tech: wrench
  dandp: circle-o-notch
  book: book
  mylinks: anchor
  tipme: gratipay

# default value for properties

defaults:
  -
    scope:
      type: "posts"
    values:
      language: "cn"
      author: "taoalpha"
  
# plugins
assets:
  dirname: assets
  baseurl: /blog/assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendors
  js_compressor: uglifier
  css_compressor: sass
  gzip: [ text/css, application/javascript ]
